"""add sessions.user_id owner fk

Revision ID: c9d094522790
Revises: d60ff0269525
Create Date: 2026-05-31 20:19:54.774310

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c9d094522790"
down_revision: str | Sequence[str] | None = "d60ff0269525"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("sessions", sa.Column("user_id", sa.Uuid(), nullable=True))
    op.create_index(op.f("ix_sessions_user_id"), "sessions", ["user_id"], unique=False)
    op.create_foreign_key(None, "sessions", "users", ["user_id"], ["id"], ondelete="CASCADE")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "sessions", type_="foreignkey")
    # if_exists=True: resilient when index was created outside Alembic (e.g. create_all in tests)
    op.drop_index(op.f("ix_sessions_user_id"), table_name="sessions", if_exists=True)
    op.drop_column("sessions", "user_id")
    # ### end Alembic commands ###
